#!/bin/bash

# Add iptables rules for masquerading and MSS clamping
iptables -t nat -A POSTROUTING -o ppp0 -j MASQUERADE
iptables -I FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu

# Set up ipv6 forwarding rules
sysctl net.ipv6.conf.all.forwarding=1
sysctl net.ipv6.conf.ppp0.accept_ra=2
